
import '../../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import PasswordContext from '@/globalContex'
import { useState } from 'react'
import AdminNavBar from '@/app/components/AdminNavBar'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
 
  return (
    <html lang="en">
      <body className={inter.className}>
       <AdminNavBar/>
        {children}
        
        </body>
    </html>
  )
}
